### PR TITLE
more efficient watching command for tests (test:watch2)

### PR DESCRIPTION
**Pull request by mindreframer**
problem: 
- recompiling typescript from scratch takes some time

solution: 
- use typescript compiler in `watch` mode
- combine commands with `&` so they both run in parallel 
and shutdown in parallel
- this gives a really nice and quick feedback loop for development

### CODE REVIEW

**Comment by jeffijoe** [comment]
Just so I understand, all you want is to run `tsc` in watch-mode when running tests in watch-mode?

There might be a race condition then, if the tests run before `tsc` is done compiling new sources. Thoughts?

**Comment by mindreframer** [comment]
@jeffijoe you are right! I did not care about this, because it was just for continuous development and the race condition would happen only during start. I just care about tests re-running quickly after code editing. 


but if you wish, here is a very verbose and race condition-safe command: 

`rimraf .test-out && tsc  --skipLibCheck -p test && (tsc  --skipLibCheck -p test  --watch & nodemon -e js,ts --exec mocha .test-out/test/**/*.spec.js --require .test-out/test/index.js)`

Thoughts? :)

**Comment by jeffijoe** [comment]
When run in parallel in watch-mode, do the outputs of both Mocha and TSC not clash in the terminal?

**Comment by mindreframer** [comment]
Just try it. ))) Really quick answer

**Comment by jeffijoe** [comment]
I'll take your word for it. 😄 Thanks!

**Pull request merged**
